version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements-dev.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py