[tool.ruff]
extend-include = ["*.ipynb"]
exclude = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    ".env",
    "_build",
    "buck-out",
    "build",
    "dist",
    "codeseeder.out",
]
line-length = 120
target-version = "py38"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "DTZ"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"docs/*" = ["E402"]

[tool.mypy]
python_version = "3.8"
strict = true
ignore_missing_imports = true
disallow_untyped_decorators = false
exclude = "codeseeder.out/|example/|tests/"

[tool.pytest.ini_options]
addopts = "-v --cov=. --cov-report term"
pythonpath = [
  "."
]

[tool.coverage.run]
omit = [
    "tests/*",
    "setup.py"
]

[tool.coverage.report]
fail_under = 80.0
