version: 0.2
env:
  variables:
    TWINE_USERNAME: __token__
  secrets-manager:
    TWINE_PASSWORD: aws-codeseeder-deployment-secrets:PyPiApiKey
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12
    commands:
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements-dev.txt
  pre_build:
    commands:
      - . .venv/bin/activate
      - pyroma .
  build:
    commands:
      - . .venv/bin/activate
      - python setup.py bdist_wheel
  post_build:
    commands:
      - twine upload dist/*
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
